config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  resources :docs
  authenticated :user do
    root "docs#index", as: "authenticated_root"
  end

end

app/models/doc.rb
class Doc < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
    before_action :find_doc, only:[:show,:edit,:update, :destroy]
    
    
    def index
        @docu= Doc.where(user_id: current_user)#Doc.all.order('created_at ASC')
    end
    def new 
        @docu= current_user.docs.build #Doc.new
    end
    def create
         @docu=current_user.docs.build(doc_params) #Doc.new(doc_params)
         if @docu.save
             redirect_to @docu
         else
             render 'new'
         end
    end
    def show
    end
    
    def edit
    end
    def update 
        if @doc.update(doc_params)
            redirect_to @doc
        else
            render 'edit'
        end 
    end
    def destroy
        @docu.destroy
        redirect_to docs_path
    end
       
    private
        def find_doc
            @docu= Doc.find(params[:id])
        end
        def doc_params
            params.require(:doc).permit(:title,:content)
        end
       
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
= simple_form_for @docu do |f|
    %fieldset{class:'form-group'}
        =f.label :title,'Título'
        %br
        =f.text_field :title,class:'form-control'
    .form-group
        =f.label :content,'Contenido'
        %br
        =f.text_area :content,class:'form-control'
    =f.button :submit,"Guardar"

app/views/docs/edit.html.haml
%h1 Editar documento
=render 'form'

=link_to "Cancelar", doc_path

app/views/docs/index.html.haml
- @docu.each do |d|
    %div{class:'col-sm-6'}
        %div{class:'panel panel-default'}
            %div{class:'panel-heading'}
                %a{href:(url_for [d])}
                    %h3= d.title
            %div{class:'panel-body'}
                %p=  truncate(d.content,length:50)  
                %span.badge= time_tag(d.created_at)

app/views/docs/new.html.haml
%h1 Nuevo documento
=render 'form'

=link_to "Cancelar", root_path

app/views/docs/show.html.haml
%h1 Detalles Documento
%div
    %h3{class: "page-header"}= @docu.title
    %span.badge= @docu.created_at
%div.well=@docu.content

=link_to "Documentos", docs_path, class: "btn btn-primary"
=link_to "Editar Documento", edit_doc_path(@docu), class: "btn"
=link_to "Eliminar Documento", doc_path(@docu),method: :delete, data: {confirm: "Confirmar eliminación"}, class: "btn"

app/views/layouts/application.html.haml
%html
%head
    %title Docu App
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true 
    = csrf_meta_tags 
%body
    %header{class:'navbar navbar-inverse navbar-fixed-top'}
        %div{class:'container'}
            %div{class: 'navbar-header'}
                %a{href: (url_for root_path), class:'navbar-brand'}
                    'DOCAPP'
            %ul{class:'nav navbar-nav'}
                %li
                    =link_to "Ver Notas", docs_path                
                - if user_signed_in?
                    %li
                        =link_to "Crear Nota", new_doc_path
                    %li
                        =link_to "Salir", destroy_user_session_path,method: :delete                        
                -else
                    %li
                        =link_to "Ingresar",  new_user_session_path
    .container
        %p.notice= notice
        %p.alert=alert
        =yield

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/welcome/index.html.haml
%div.jumbotron
    %h1="Docapp"
    %p.lead='Tus notas online'
    =link_to "Registrarme Ya",new_user_session_path,role:'button', class:'btn btn-lg btn-success'